# Generated by Django 4.2.16 on 2024-09-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article_description_article_description_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
    ]
