# Generated by Django 4.2.16 on 2024-09-28 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='url'),
        ),
    ]
